site_name: The Cafe
theme:
  name: material
  # name: alabaster
  # font: false
# repo_url: https://github.com/tonygilkerson/cafe
plugins:
  # - simple:
  - mermaid2:
  - search:
nav:
  - Home Assistant: https://ha.tonygilkerson.us
  - Notebook: https://notebook.tonygilkerson.us
  - httpbin: https://httpbin.tonygilkerson.us
  - CKAD ğŸŒ: https://tonygilkerson.github.io/ckad

    

